// symbol index generated by DDOX - do not edit
var symbols = [
{name: 'bft.bf', kind: "module", path: './bft/bf.html', attributes: []},
{name: 'bft.bf.BFProgram', kind: "structdeclaration", path: './bft/bf/BFProgram.html', attributes: []},
{name: 'bft.bf.BFProgram.execute', kind: "functiondeclaration", path: './bft/bf/BFProgram.execute.html', attributes: []},
{name: 'bft.bf.BFProgram.memory', kind: "variabledeclaration", path: './bft/bf/BFProgram.memory.html', attributes: []},
{name: 'bft.bf.BFProgram.ptr', kind: "variabledeclaration", path: './bft/bf/BFProgram.ptr.html', attributes: []},
{name: 'bft.bf.transpile', kind: "functiondeclaration", path: './bft/bf/transpile.html', attributes: ["pure", "safe"]},
];
